# Use Amazon Corretto JDK 17 with Alpine
FROM amazoncorretto:17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the Spring Boot JAR file into the container
COPY target/*.jar app.jar

# Expose the application's port
EXPOSE 8090

# Run the application
CMD ["java", "-jar", "app.jar"]
